server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    url: jdbc:mysql://192.168.228.128:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: edu.hust
    ttl: 3600000