server:
  port: 9011
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: edu.hust
    ttl: 3600000
zuul:
  routes:
    tensquare-base: /base/**
    tensquare-user: /user/**
    tensquare-qa: /qa/**
    tensquare-friend: /friend/**
    tensquare-gathering: /gathering/**
    tensquare-recruit: /recruit/**
    tensquare-search: /recruit/**
    tensquare-sms: /sms/**
    tensquare-spit: /spit/**



