server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mryshen/tensquare-config.git
  rabbitmq:
    host: 192.168.228.130
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh